### ISSUE TITLE
[gpx_dump.py] Metadata file structure

### ISSUE THREAD

**Issue by Zverik** [iandees/planet-gpx-dump#4]
This is an example of metadata.xml file:

``` xml
<gpxFiles generator="OpenStreetMap gpx_dump.py" timestamp="2013-04-03T11:21:04">
<gpxFile id="1380306" timestamp="2013-01-06T09:52:27.915788" description="End of Dovercourt foot survey and return drive to Clacton via Burcarts for some smokeless coal..." points="7647" startLatitude="51.9280000" startLongitude="1.2637900" visibility="identifiable" uid="57884" filename="identifiable/1380306.gpx">
  <tag>Clacton</tag>
  <tag>Dovercourt</tag>
</gpxFile>
<gpxFile id="1429388" timestamp="2013-04-03T11:14:42.716206" description="trackable test" points="4513" startLatitude="53.0220000" startLongitude="8.8025500" visibility="trackable" filename="trackable/1429388.gpx"/>
</gpxFiles>
```

How it should look (spot the differences):

``` xml
<?xml version="1.0" encoding="utf-8"?>
<gpxFiles version="1.0" generator="OpenStreetMap gpx_dump.py" timestamp="2013-04-03T11:21:04Z">
<gpxFile id="1380306" timestamp="2013-01-06T09:52:27Z" points="7647" lat="51.9280000" lon="1.2637900" visibility="identifiable" uid="57884" user="EdLoach" filename="identifiable/1380306.gpx">
  <description>End of Dovercourt foot survey and return drive to Clacton via Burcarts for some smokeless coal...</description>
  <tag>Clacton</tag>
  <tag>Dovercourt</tag>
</gpxFile>
<gpxFile id="1429388" timestamp="2013-04-03T11:14:42Z" points="4513" lat="53.0220000" lon="8.8025500" visibility="trackable" filename="trackable/1429388.gpx">
  <description>trackable test</description>
</gpxFile>
</gpxFiles>
```

The reasoning:
- description string could be very long and contain multilanguage characters. It has more right to be a separate tag than tags or any other data.
- latitude and longitude have standard naming across all OSM files. The fact that those are starting points could be mentioned in documentation, but actually it doesn't matter.
- fractional time is useless, while it isn't inside gps tracks. I'd argue that even minutes and seconds do not matter, but let those be for the sake of ISO timestamps. Dumping those _just because we can_ would not archieve anything besides questions of why.
- usernames are the main key to the database for tools outside OSM, not uids. There are no API methods for requesting information using uids, for example. That's why user names should be provided, like in OSM XML files.
- this file format _will change_, that's why the version has to be tracked.
- I don't know if the timestamp should be present on tracks with "public" or "private" visibility, but this can, and probably should be discussed.

**Comment by iandees** [comment]
- `description` was moved to it's own element in 1ee37dd
- `startLatitude` and `startLongitude` was replaced with `lat`/`lon` in d92f657
- fractional time is being kept because there's no point in removing data at this point. Data users can drop it if they want.
- Grant ran the test dump with uid mapping turned off. It is enabled by default but takes a long time.
- Added a version number to the root of the metadata.xml file in 813ae91
- [Visibility of GPS Traces](http://wiki.openstreetmap.org/wiki/Visibility_of_GPS_traces) says that the timestamp will not show up in the GPX files and doesn't mention the "upload timestamp".

**Comment by Zverik** [comment]
Ok, so there are two points remaining. Thanks for prompt fixing :)
- You are removing parts of the data. For example, file names (which are in `name` column if I'm not mistaken). The upload time is not precise (uploading itself takes 1 to 600 seconds), so keeping fractional seconds misleads data consumers into thinking they are correct or mean anything.
- Time zones should be added to all timestamps, including generated GPX files. Since everything in the database is in UTC, as Tom states, a simple 'Z' would suffice.

**Comment by iandees** [comment]
Specifying UTC explicitly with a appended `Z` was done in b47c6f0.

**Comment by iandees** [comment]
When we start working with the original files we'll stick the real filename in there.

**Comment by Zverik** [comment]
And what of fractional seconds?
