### ISSUE TITLE
[gpx_dump.py] Write tar archive straight away

### ISSUE THREAD

**Issue by Zverik** [iandees/planet-gpx-dump#7]
Python has modules for working with tag files. The current dump format (series of gpx files followed by a `metadata.xml`) can be output sequentially into the tar file, which then can be piped to an archiver, sparing the disk those extra 3GB of gpx data.

**Comment by iandees** [comment]
Good idea, but previous thoughts on this are that we want plain text available before compression.

**Comment by Zverik** [comment]
Want? Why?
